# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Fetch
                                 A QGIS plugin
 Fetch Azure imagery based on a bounding box.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-08-23
        copyright            : (C) 2022 by Sridene
        email                : sridene@blackshark.ai
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Sridene'
__date__ = '2022-08-23'
__copyright__ = '(C) 2022 by Sridene'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Fetch class from file Fetch.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .FetchImagery import FetchPlugin
    return FetchPlugin()
